[package]
name = "runner-backend"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
default = ["mock"]
mock = []

[dependencies]
runner-common = { path = "../runner-common" }
serde = { workspace = true }

