[package]
name = "runner-core"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
runner-common = { path = "../runner-common" }
runner-backend = { path = "../runner-backend" }
serde = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }

